# Generated by Django 4.0.4 on 2022-05-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='expirationTime',
            new_name='timestamp',
        ),
    ]
